Start shooter
Swartdogs/CrescendoCode pull request #13
Opened 2024-02-09 00:07 UTC by TheWonderfulWit

… one

2024-02-09 01:56 UTC, edenreicherts requested changes
Some small changes but overall good job!

2024-02-09 01:56 UTC, edenreicherts commented on src/main/java/frc/robot/Constants.java
> +            // TODO Auto-generated method stub
This is auto generated and we will probably want to delete it

2024-02-09 01:56 UTC, edenreicherts commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +public class CompositeCommands extends Command
We'll want to remove extends commands and we will want to make it final

2024-02-09 01:56 UTC, edenreicherts commented on src/main/java/frc/robot/RobotContainer.java
> +        double upperVelocity = 1;
We aren't using these so we can delete them

2024-02-09 02:15 UTC, L-Cedric requested changes

2024-02-09 02:15 UTC, L-Cedric commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        return Commands.parallel(NotepathCommands.startFeed(notepath), ShooterFlywheelCommands.shooterFlywheelShoot(shooterFlywheel, lowerVelocity, upperVelocity)).finallyDo(() ->
We will want to add, before the .finallyDo, a "andThen" which shuts off when we no longer have a note.

2024-02-09 02:32 UTC, edenreicherts approved these changes, later dismissed

2024-02-09 21:27 UTC, L-Cedric approved these changes, later dismissed

2024-02-09 21:27 UTC, cedricliu07 commented on src/main/java/frc/robot/RobotContainer.java
> +        _controller.rightTrigger().onTrue(CompositeCommands.start(_shooterFlywheel, _notepath, 1, 1));
Add Cancel Function

2024-02-09 22:11 UTC, CanineSatsuma6 requested changes

2024-02-09 22:11 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        });
There's two main issues here:

1. Both of the commands in the parallel command execute and then immediately finish. The only thing after that is a `finallyDo` which will then run essentially immediately, which shuts the shooter off. When we test this, we'll see the robot essentially do nothing because it's starting then immediately stopping

2. Conceptually, this command turns on the shooter and the notepath at the same time. We don't want to do that.

   The main reason we don't is because we need to make sure the shooter flywheel has actually sped up before we try to fire a note. Since we need to wait before firing, we may find ourselves in a situation where the drivers want to "rev up" the shooter while on their way to where they plan to shoot from. They'll need a way to let the robot know they're ready to fire.

I propose we split this into two commands.

The first command will:
1. set the shooter velocity
2. wait until we don't have a note anymore
3. shut off the shooter

The second command will:
1. wait until the shooter is up to speed
2. turn on the notepath
3. wait until we don't have a note anymore
4. shut off the notepath

The second command should be implemented in such a way that it doesn't care what velocity the shooter flywheel is spinning at, just that the flywheel is "at speed". To do this, we'll need to add a method to the `ShooterFlywheel` subsystem that checks if the current velocity is within a certain range of the expected velocity. That range should have a constant in Constants.java and the range should also be configurable through the dashboard.

2024-02-09 22:11 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +    }
If we have the two commands from the last message, I'm not sure we need this. Both of those two commands are individually responsible for the notepath and the shooter, so there's not much reason for a joint command that stops both

2024-02-09 22:11 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/Constants.java
> +
Super small nitpick, let's remove these extra lines

2024-02-10 19:55 UTC, CanineSatsuma6 approved these changes

2024-02-10 19:56 UTC, SAKETH11111 approved these changes
Good!

2024-02-10 19:56 UTC, L-Cedric approved these changes
looks good :D

2024-02-10 19:57 UTC, merged

2024-02-10 19:57 UTC, GreatGreenStar approved these changes