Commands starting and stopping intake and notepath
Swartdogs/CrescendoCode pull request #14
Opened 2024-02-09 01:53 UTC by L-Cedric

- Created commands to start and stop intake and notepath
- Tied those commands to buttons in robot container

2024-02-09 21:21 UTC, CanineSatsuma6 requested changes

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/notepath/NotepathIO.java
> +        public boolean  hasNote                      = true;
Let's default this to false instead

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/Constants.java
> +        public static final double FLYWHEEL_INTAKE_SPEED = 2000;
@SAKETH11111, FYI, this will need to be added as a setting to the settings page on the dashboard. This setting should also be converted from a velocity to a percent output

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +                ShooterFlywheelCommands.shooterFlywheelShoot(shooterFlywheel, -Constants.ShooterFlywheel.FLYWHEEL_INTAKE_SPEED, -Constants.ShooterFlywheel.FLYWHEEL_INTAKE_SPEED), NotepathCommands.rev
Rather than setting the shooter to a specific velocity to intake a note, we should set its voltage directly. We'll need a new command in `ShooterCommands` for setting the flywheel voltages.

Don't forget to make the intake voltage configurable for the dashboard. The dashboard should also specify the speeds as a percentage, not a voltage.

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/Constants.java
> +        public static final double     BED_PICKUP_ANGLE = 60;
It's likely we won't be able to pick up a note through the intake with the shooter bed at any angle. We'll likely need to move the bed to an angle to pick up through the intake, and we'll definitely need to adjust the bed to pick up through the shooter. These may NOT be the same angle, so let's make another constant to distinguish between them

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +            shooterFlywheel.setLowerVelocity(0);
```suggestion
            shooterFlywheel.stop();
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        ).andThen(Commands.waitUntil(() -> notepath.hasNote())).finallyDo(() ->
Here's a bit of an odd sequence:

The light sensor that tells us we have a note is located between the notepath and the shooter flywheel. When intaking through the shooter, we can't stop the motors when the light sensor trips because the note will still be hanging halfway out of the shooter flywheel at that point. We actually want to make sure we shut everything off once we no longer see a note.

The tricky part is the "no longer" part. We have to first see a note, then we have to stop seeing it. I think that would look something like this:

```suggestion
        ).andThen(Commands.waitUntil(() -> notepath.hasNote())).andThen(Commands.waitUntil(() -> !notepath.hasNote())).finallyDo(() ->
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        ).andThen(Commands.waitUntil(() -> notepath.hasNote())).finallyDo(() ->
Another thing to consider is that we can't necessarily rely on the light sensor to directly tell us we have a note. If we pick up through the intake, we stop when the sensor is tripped. If we pick up through the shooter, we stop when the sensor is NOT tripped. In both cases, we'll have a note, but the sensor state doesn't directly reflect that.

I'm wondering if we need to split apart the logic that says we have a note from the logic that says whether the sensor is tripped or not.

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        });
This command looks fine, but we only want to be able to pick up a note if we don't already have one. I'm thinking we need to add something like this:

```suggestion
        return Commands.parallel(IntakeCommands.startIntake(intake), NotepathCommands.intakePickup(notepath)).andThen(Commands.waitUntil(() -> notepath.hasNote())).finallyDo(() ->
        {
            intake.setIntakeOff();
            notepath.setOff();
        }).unless(() -> notepath.hasNote());
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CompositeCommands.java
> +        });
```suggestion
        }).unless(() -> notepath.hasNote());
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/RobotContainer.java
> +        _controller.y().onTrue(CompositeCommands.intakePickup(_intake, _notepath).andThen(CompositeCommands.stopIntaking(_intake, _notepath)));
We don't need to tell it to stop intaking. The composite command already takes care of this

```suggestion
        _controller.y().onTrue(CompositeCommands.intakePickup(_intake, _notepath));
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/RobotContainer.java
> +        _controller.a().onTrue(CompositeCommands.shooterPickup(_shooterBed, _shooterFlywheel, _notepath).andThen(IntakeCommands.stopIntake(_intake)));
Same here:

```suggestion
        _controller.a().onTrue(CompositeCommands.shooterPickup(_shooterBed, _shooterFlywheel, _notepath));
```

2024-02-09 21:21 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/RobotContainer.java
> +        _controller.b().onTrue(IntakeCommands.reverseIntake(_intake).until(() -> !_controller.b().getAsBoolean()).andThen(IntakeCommands.stopIntake(_intake)));
I know you didn't change this line (it changed in a different PR), but we should match what's in main. This line has the potential to crash the code by modifying the button loop in some very specific circumstances we didn't completely figure out:

```suggestion
        _controller.b().whileTrue(IntakeCommands.reverseIntake(_intake).andThen(Commands.idle(_intake)).finallyDo(() -> _intake.setIntakeOff()));
```

2024-02-10 01:55 UTC, CanineSatsuma6 approved these changes
5$

2024-02-10 01:58 UTC, SAKETH11111 approved these changes
0111010001101000011010010111001100100000011001110110111101100100

2024-02-10 02:01 UTC, merged