Code for the Robot field position from april tag
Swartdogs/CrescendoCode pull request #5
Opened 2024-01-17 04:11 UTC by SAKETH11111

In this code, we implemented a Vision subsystem using PhotonVision, with a PhotonCamera and PhotonPoseEstimator, to periodically update and log the estimated global pose of the robot.

2024-01-18 04:39 UTC, CanineSatsuma6 requested changes
A couple small things, but you're really close. Nice job!

2024-01-18 04:39 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/Robot.java
> +import edu.wpi.first.apriltag.AprilTagFieldLayout;
We can revert all of the changes in this file. As is, we'll constantly be scanning for April Tags when the robot starts up, but we disabled the command scheduler, so none of our other control logic will actually execute

2024-01-18 04:39 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/vision/Vision.java
> +                /* AprilTagFieldLayout */ null,
We'll want to load the `AprilTagFieldLayout` object in the same way you're currently doing in Robot.java right now

2024-01-18 04:39 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonlib.java
> +  }
We don't have LEDs on our Pi/camera, so we can get rid of this method.

2024-01-18 04:39 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/vision/VisionIO.java
> +  public default void setPipeline(int pipeline) {}
We don't have LEDs, and we'll only have one pipeline, so we don't need either of these methods.

2024-01-18 04:39 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/vision/VisionIO.java
> +    public double simpleAngle = 0.0;
We don't use these inputs, and I'm not sure what they represent, so we can remove these as well

2024-01-18 05:31 UTC, edenreicherts reviewed
Other than the changes that were previously mentioned, I didn't notice anything to adjust! Great work!

2024-01-18 22:42 UTC, SAKETH11111 commented
Thanks for the comments, Collin. I have made the changes according to comments and I think it is good to go! 😊

2024-01-19 01:37 UTC, cedricliu07 requested changes
Good, formatting is slightly off  though in vision and visionphoton

2024-01-19 01:52 UTC, L-Cedric submitted a review, later dismissed
Good Changes :D

2024-02-01 00:21 UTC, TheWonderfulWit commented on src/main/java/frc/robot/Constants.java
> +        public static final int PARAMETER_Y = (int)Units.inchesToMeters(0);
The camera is not on the ground shouldn't it be above 0

2024-02-01 00:31 UTC, TheWonderfulWit submitted a review, later dismissed
I didn't see any problems good job

2024-02-04 21:32 UTC, AbbySliwinski requested changes

2024-02-04 21:32 UTC, AbbySliwinski commented on src/main/java/frc/robot/RobotContainer.java
> +    private Vision         _vision;
make final and add a warning suppression statement

2024-02-04 21:32 UTC, AbbySliwinski commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonlib.java
> +            Optional<EstimatedRobotPose> estimatedPose = getEstimatedGlobalPose(_lastPose, result);
add white space

2024-02-04 21:32 UTC, AbbySliwinski commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonlib.java
> +            if (estimatedPose.isPresent())
create local variable for has pose and update global variable in synchronized

2024-02-04 21:32 UTC, AbbySliwinski commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonlib.java
> +    private Pose2d              _lastPose;
make new pose2D

2024-02-04 22:06 UTC, AbbySliwinski approved these changes

2024-02-04 22:06 UTC, CanineSatsuma6 approved these changes

2024-02-04 22:08 UTC, merged